name: Release
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
          registry-url: https://registry.npmjs.org/
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Build
        run: |
          yarn install
          yarn build
      - name: publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.HUOGUI_NPM_TOKEN}}
      - name: Read version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version
      - name: Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.HUOGUI_TOKEN }}
        with:
          tag_name: v${{steps.version.outputs.value}}
          release_name: v${{steps.version.outputs.value}}
          body: body_v${{steps.version.outputs.value}}
          draft: false
          prerelease: false